/*
    KPI 15:
    Ratio de Tiempo de Vuelo en el Aire-Tiempo en Tierra por aerolínea hacia 
    los distintos Estados de destino entre 2019-2023.
*/

select
    *
from
    hecho_vuelos
JOIN AIRLINES ON HECHO_VUELOS.CODE_AIRLINE = AIRLINES.CODE_AIRLINE
JOIN STATES ON HECHO_VUELOS.CODE_STATE_DEST = STATES.CODE_STATE
JOIN  DAYS ON HECHO_VUELOS.ID_DAY = DAYS.ID_DAY
JOIN  MONTHS ON DAYS.ID_MONTH = MONTHS.ID_MONTH
JOIN  YEARS ON MONTHS.ID_YEAR = YEARS.ID_YEAR
WHERE
    YEARS.ID_YEAR BETWEEN 2019 AND 2023