/* Entrega la cantida de vuelos completado cancelados por aerolínea entre 2019-2023 */
SELECT 
    AIRLINES.airline, 
    YEARS.ID_YEAR, 
    COUNT(CASE WHEN STATE_FLIGHTS.TYPE_STATE_FLIGHTS = 'completed flight' THEN 1 ELSE NULL END) AS COMPLETED_FLIGHTS_COUNT,
    COUNT(CASE WHEN STATE_FLIGHTS.TYPE_STATE_FLIGHTS = 'cancelled' THEN 1 ELSE NULL END) AS CANCELLED_FLIGHTS_COUNT,
    COUNT(CASE WHEN STATE_FLIGHTS.TYPE_STATE_FLIGHTS = 'diverted' THEN 1 ELSE NULL END) AS DIVERTED_FLIGHTS_COUNT,
    COUNT(CASE WHEN STATE_FLIGHTS.TYPE_STATE_FLIGHTS) AS FLIGHTS_COUNT
FROM
    hecho_vuelos
JOIN 
    AIRLINES ON hecho_vuelos.code_airline  = AIRLINES.CODE_AIRLINE
JOIN
    DAYS ON hecho_vuelos.ID_DAY = DAYS.ID_DAY
JOIN
    MONTHS ON DAYS.ID_MONTH = MONTHS.ID_MONTH
JOIN    
    YEARS ON MONTHS.ID_YEAR = YEARS.ID_YEAR
JOIN
    STATE_FLIGHTS ON hecho_vuelos.ID_STATE_FLIGHTS = STATE_FLIGHTS.ID_STATE_FLIGHTS
WHERE
    (YEARS.FL_YEAR BETWEEN 2019 AND 2023)
GROUP BY
    AIRLINES.airline, YEARS.ID_YEAR;
    
/* KPI2 ahhh */
SELECT 
    AIRLINES.airline, 
    YEARS.ID_YEAR, 
    COUNT(CASE WHEN STATE_FLIGHTS.TYPE_STATE_FLIGHTS = 'completed flight' THEN 1 ELSE NULL END) * 1.0 / COUNT(*) AS COMPLETED_FLIGHTS_PERCENTAGE
FROM
    hecho_vuelos
JOIN 
    AIRLINES ON hecho_vuelos.code_airline  = AIRLINES.CODE_AIRLINE
JOIN
    DAYS ON hecho_vuelos.ID_DAY = DAYS.ID_DAY
JOIN
    MONTHS ON DAYS.ID_MONTH = MONTHS.ID_MONTH
JOIN    
    YEARS ON MONTHS.ID_YEAR = YEARS.ID_YEAR
JOIN
    STATE_FLIGHTS ON hecho_vuelos.ID_STATE_FLIGHTS = STATE_FLIGHTS.ID_STATE_FLIGHTS
WHERE
    (YEARS.FL_YEAR BETWEEN 2019 AND 2023)
GROUP BY
    AIRLINES.airline, YEARS.ID_YEAR;